### ISSUE TITLE
Integrate CI Github Action

### ISSUE THREAD

**Issue by viethoangat01** [viethoangat01/task-management-backend#10]
# Goal  

- [x]  Setup PR CI build: Create` .github/workflows/ci.yml`

- [x]  Add Checkstyle to enforce code style: Push messy code to see warnings

- [x]  Add Gitleaks to scan for credentials: Test by committing a fake token

- [x]  Add OWASP check for dependencies: Review scan output in PR checks

# Details  
## Part 1: CI Setup – Build & Test on Each Pull Request
**Goal**:  Automatically verify build and test success on every PR to `main `or `develop`.
**Setup Instructions**:
```
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x ./gradlew
      - run: ./gradlew build
```
**Expected Result**:
- [x] When you create a PR to main or develop, GitHub will show a ✅ “CI - Build & Test” check.

- [x] You can view detailed output under the "Actions" tab.

- [x] If tests fail, GitHub will block the merge with ❌.

## Part 2: Enforce Code Style with Checkstyle Bot
**Goal**:  Automatically validate code formatting and style rules on PRs.
**Setup Instructions**:

1. Add Checkstyle to your `build.gradle.kts`:
```
plugins {
    checkstyle
}

checkstyle {
    toolVersion = "10.3.2"
    configFile = file("config/checkstyle/checkstyle.xml")
}
```
2. Add Google's [checkstyle.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) to `config/checkstyle/checkstyle.xml`.
3. Update your CI workflow:
```
- name: Check Java Style (Checkstyle)
  run: ./gradlew checkstyleMain checkstyleTest
```
**Expected Result**:
- [x] On PRs, GitHub Actions will show code style check step.
- [x] Violations will appear in the console log of the “Actions” tab.
- [x] Your PR should be blocked if critical style checks fail (depends on config).
### A. Detect Secrets with Gitleaks
**Goal**:  Prevent accidental commits of tokens, passwords, or credentials.
**Setup Instructions**:
```
- name: Scan for Secrets
  uses: gitleaks/gitleaks-action@v2
```
**Expected Result**:
- [x] On PR, GitHub Actions will scan for secrets.
- [x] If a secret is detected, the workflow will fail.
- [x] You will see the secret type and file path in the Action logs.
### B. Scan Dependencies with OWASP Dependency-Check
**Goal**:  Alert for known vulnerable dependencies in` build.gradle.kts`.
**Setup Instructions**:
```
- name: OWASP Dependency Check
  uses: dependency-check/Dependency-Check_Action@main
  with:
    project: 'spring-boot'
    format: 'HTML'
```
**Expected Result**:
- [x] Workflow runs dependency analysis.
- [x] If vulnerabilities exist, they’re listed in the console or HTML report (available in artifacts).
- [x] You can download the report under "Artifacts" after a PR build finishes.
